# Generated by Django 2.0.4 on 2018-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0002_latexfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latexfile',
            name='title',
            field=models.CharField(default='FOSURE', max_length=200),
        ),
    ]
