# Generated by Django 2.0.4 on 2018-04-20 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatexFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex', models.FileField(upload_to='', verbose_name='Uploaded Latex File')),
                ('created_ar', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
